name: Build and Release .NET App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release

      - name: Read Version from Project File
        id: get_version
        shell: pwsh
        run: |
          $version = Select-String -Path AmblyopiaSaber.csproj -Pattern '<Version>(.*?)<\/Version>' | ForEach-Object { $_.Matches.Groups[1].Value }
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Debug: Check Build Output
        shell: pwsh
        run: |
          Write-Host "🔍 Checking built files..."
          Get-ChildItem -Path bin/Release -Recurse

      - name: Create Release Archive
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path release -Force
          Compress-Archive -Path bin/Release/Final/Plugins/* -DestinationPath release/AmblyopiaSaber-${{ env.VERSION }}.zip -Force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: release/AmblyopiaSaber-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
