name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Löst den Workflow nur bei Tags aus, die mit "v" beginnen (z.B. v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Stelle sicher, dass du die richtige Version nutzt

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish --configuration Release --output out

      - name: Create ZIP file
        run: |
          mkdir release
          zip -r release/AmblyopiaSaber-${{ github.ref_name }}.zip out/

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AmblyopiaSaber-${{ github.ref_name }}
          path: release/AmblyopiaSaber-${{ github.ref_name }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: AmblyopiaSaber-${{ github.ref_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: AmblyopiaSaber-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
